[tool.black]
# work !
line-length = 180

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = ["no_parallel: Tests that must not be run in parallel"]